"""Periodic synthesis job — reads latest DB state, writes a markdown summary
into analysis_runs. Fires macOS notification on material changes.

The body is generated by the local `claude` CLI when available (uses user's
Max subscription via `claude --bare -p`); falls back to a rule-based template
if the CLI is missing or times out. The headline + alert detection is always
rule-based for reliability.
"""
from __future__ import annotations

import asyncio
import logging
import shutil
from datetime import datetime, timedelta
from typing import Any

from .config import ALERT_THRESHOLDS
from .db import (
    current_positions,
    get_conn,
    latest_eia,
    latest_prices,
    latest_spreads,
    recent_episodes,
    recent_news,
)
from .notifications import notify
from .trades import annotate_positions

logger = logging.getLogger(__name__)

CLAUDE_CLI = shutil.which("claude") or "/opt/homebrew/bin/claude"
CLAUDE_TIMEOUT_SECONDS = 240


def _build_data_context() -> dict:
    """Collect the latest state across all data sources for synthesis input."""
    return {
        "prices": latest_prices(),
        "spreads": latest_spreads(),
        "episodes": recent_episodes(limit=5),
        "news": recent_news(limit=20),
        "positions": annotate_positions(
            current_positions(sec_types=("FUT", "OPT"))
        ),
        "enriched_news": _enriched_news_for_prompt(limit=15, body_chars=1800),
        "transcript_excerpts": _transcript_excerpts(limit=3, chars=2500),
        "eia": latest_eia(),
        "sparta_trades": _sparta_trade_ideas_for_prompt(episode_limit=3),
    }


def _sparta_trade_ideas_for_prompt(episode_limit: int = 2) -> list[dict]:
    """High-conviction Sparta trade ideas (HIGH + medium-high) from last N episodes.

    Drops 'medium' and 'low' per user's filter preference. The most-recent
    episode should receive primary emphasis in the synthesis.
    """
    from .db import trade_ideas_chronological
    return trade_ideas_chronological(
        limit=200, episode_limit=episode_limit, high_conviction_only=True,
    )


def _enriched_news_for_prompt(limit: int, body_chars: int) -> list[dict]:
    """Pull the most recent news rows that have body text. Truncated to fit
    in the prompt token budget."""
    with get_conn() as conn:
        rows = conn.execute(
            """
            SELECT title, source, url, body, published_at, fetched_at
            FROM news
            WHERE body IS NOT NULL AND LENGTH(body) > 300
            ORDER BY COALESCE(published_at, fetched_at) DESC
            LIMIT ?
            """,
            [limit],
        ).fetchall()
    return [
        {
            "title": r[0], "source": r[1], "url": r[2],
            "body": (r[3] or "")[:body_chars],
            "published_at": r[4], "fetched_at": r[5],
        }
        for r in rows
    ]


def _transcript_excerpts(limit: int, chars: int) -> list[dict]:
    """Newest podcast transcripts truncated per-episode."""
    with get_conn() as conn:
        rows = conn.execute(
            """
            SELECT number, title, transcript, published_at
            FROM episodes
            WHERE transcript IS NOT NULL AND LENGTH(transcript) > 500
            ORDER BY COALESCE(published_at, fetched_at) DESC
            LIMIT ?
            """,
            [limit],
        ).fetchall()
    return [
        {
            "number": r[0], "title": r[1],
            "transcript": (r[2] or "")[:chars],
            "published_at": r[3],
        }
        for r in rows
    ]


def _compute_headline_and_alert(data: dict) -> tuple[str, bool]:
    """Always rule-based — Claude is for body text, not alert logic."""
    biggest = None
    for p in data["prices"]:
        if p.get("change_pct") is None:
            continue
        if biggest is None or abs(p["change_pct"]) > abs(biggest["change_pct"]):
            biggest = p

    parts: list[str] = []
    triggered = False
    if biggest:
        sign = "+" if biggest["change_pct"] > 0 else ""
        parts.append(
            f"{biggest['instrument']} {sign}{biggest['change_pct']:.2f}% "
            f"(${biggest['price']:.2f})"
        )
        if abs(biggest["change_pct"]) >= ALERT_THRESHOLDS["brent_pct_move"]:
            triggered = True

    eps = data["episodes"]
    if eps and eps[0].get("number") and eps[0]["number"] >= 93:
        parts.append(f"Sparta Ep {eps[0]['number']} dropped")
        triggered = True

    return (" · ".join(parts) if parts else "No material change."), triggered


def _rule_based_body(data: dict) -> str:
    """Fallback body when claude CLI unavailable or times out."""
    lines = [
        f"# Live snapshot — {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "## Prices",
    ]
    for p in data["prices"]:
        chg = (f"{p['change_pct']:+.2f}%" if p.get("change_pct") is not None
               else "—")
        lines.append(
            f"- **{p['instrument']}** ({p.get('contract', '')}): "
            f"${p['price']:.4f} ({chg}) [close ${p.get('prev_close') or 0:.4f}]"
        )
    if data["spreads"]:
        lines += ["", "## Spreads"]
        for s in data["spreads"]:
            lines.append(
                f"- **{s['name']}**: {s['value']:+.3f} {s['unit']} — {s['note']}"
            )
    if data["positions"]:
        lines += ["", "## Open positions (FUT + OPT)"]
        for p in data["positions"][:20]:
            pnl = (f"{p['unrealized_pnl']:+,.0f}" if p.get("unrealized_pnl")
                   is not None else "—")
            tag = p.get("thesis") or ""
            lines.append(
                f"- **{p['symbol']}** {p.get('local_symbol', '')}: "
                f"qty {p['position']:g}, unr P&L {pnl}"
                f"{' — ' + tag if tag else ''}"
            )
    if data["episodes"]:
        lines += ["", "## Latest podcast episodes"]
        for e in data["episodes"]:
            lines.append(f"- Ep {e.get('number', '?')}: {e['title']}")
    if data["news"]:
        lines += ["", "## Recent news"]
        for n in data["news"][:10]:
            lines.append(f"- [{n['source']}] {n['title']}")
    return "\n".join(lines)


def _build_claude_prompt(data: dict) -> str:
    """Compact prompt for the claude CLI — keeps token count reasonable."""
    prices_md = "\n".join(
        f"- {p['instrument']} ({p.get('contract', '?')}): "
        f"${p['price']:.4f} "
        f"({p['change_pct']:+.2f}% from close ${p.get('prev_close') or 0:.4f})"
        for p in data["prices"] if p.get("price")
    )
    spreads_md = "\n".join(
        f"- {s['name']}: {s['value']:+.3f} {s['unit']}"
        for s in data["spreads"]
    )
    eia_md = "\n".join(
        f"- {o['label']} ({o['period']}): {o['value']:,.0f} {o['unit'] or ''}"
        f" (chg w/w: {(o['value'] - o['prev_value']):+,.0f})" if o.get('prev_value') is not None
        else f"- {o['label']} ({o['period']}): {o['value']:,.0f} {o['unit'] or ''}"
        for o in data.get("eia", [])
    )

    # Sparta trade ideas — group by episode, label most-recent as PRIMARY
    sparta_lines: list[str] = []
    current_ep: int | None = None
    sparta_trades = data.get("sparta_trades", [])
    most_recent_ep = (max((t.get("episode_number") or 0) for t in sparta_trades)
                      if sparta_trades else None)
    for t in sparta_trades:
        ep = t.get("episode_number")
        if ep != current_ep:
            tag = " — **PRIMARY (most recent)**" if ep == most_recent_ep else " — supporting"
            sparta_lines.append(f"\n### Ep {ep}: {t.get('episode_title','')[:70]}{tag}")
            current_ep = ep
        flag = "IBKR" if t.get("executable_on_ibkr") else "framework"
        expr = t.get("ibkr_expression") or "(no expression captured)"
        sparta_lines.append(
            f"- [{(t.get('conviction') or '?').upper()}] "
            f"{(t.get('direction') or '?').upper()} {t.get('instrument','?')} "
            f"({t.get('person','?')}) [{flag}] — Expression: {expr} — {t.get('rationale','')}"
        )
    sparta_md = "\n".join(sparta_lines) if sparta_lines else "(no high-conviction Sparta trades extracted)"
    positions_md = "\n".join(
        f"- {p['symbol']} {p.get('local_symbol', '')}: qty {p['position']:g}, "
        f"unr P&L {p.get('unrealized_pnl') or 0:+.0f}"
        f"{' — ' + p['thesis'] if p.get('thesis') else ''}"
        for p in data["positions"][:15]
    )
    # Headlines-only feed (for breadth)
    news_md = "\n".join(
        f"- [{n['source']}] {n['title']}" for n in data["news"][:15]
    )

    # Enriched articles — title + body excerpt — only the ones we actually
    # have full text for. This is the meaningful content.
    enriched_blocks = []
    for n in data.get("enriched_news", []):
        body = n["body"].replace("\n\n", "\n").strip()
        enriched_blocks.append(
            f"### [{n['source']}] {n['title']}\n{body}\n"
        )
    enriched_md = "\n".join(enriched_blocks) if enriched_blocks else "(no enriched articles yet)"

    # Podcast transcripts
    transcript_blocks = []
    for e in data.get("transcript_excerpts", []):
        excerpt = e["transcript"].replace("\n", " ")
        transcript_blocks.append(
            f"### Sparta Ep {e['number']}: {e['title']}\n{excerpt}\n"
        )
    transcripts_md = "\n".join(transcript_blocks) if transcript_blocks else "(no transcripts yet)"

    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    return f"""You are a commodity research analyst summarizing the live state of an
oil/distillate trade book. Write a markdown digest with these EXACT sections in order:

## What materially changed
Specific moves in prices/spreads vs prior session, cite levels.

## Active Sparta trade book — last 2 episodes (HIGH + medium-high only)
**Enumerate EVERY high-conviction Sparta trade idea in the input below**, grouped
by episode (newest first). Place PRIMARY EMPHASIS on the most-recent episode —
treat it as the live framework; the prior episode is supporting context.

For each: direction, instrument, conviction, person, IBKR-tradable flag, the
IBKR contract expression (or framework reason), AND any relation_to_prior tag
(reverses / offsets / parks / reiterates / elevates) with the relation note.

Format each as:
`- [CONV] DIR Instrument (Person) [IBKR/framework] — Expression: X — Rel: TAG (note) — Rationale`

## Reversals & shifts
After the trade-book enumeration, add a dedicated **Reversals & shifts** sub-
section listing every idea in the most recent episode where `relation_to_prior`
is one of `reverses`, `offsets`, or `parks`. This is the change-vs-prior view —
critical for spotting when Sparta backs away from a call.

## Position alignment
For each of the user's current positions (in the Open Positions section
below), state whether today's Sparta calls support, contradict, or are
silent. Reference the trade-book IDs (#3 GO/Brent crack, #6 HOGO, #10
back-end Brent, #14 ARA-PAD1) only where you have direct mapping.

## What to watch
Specific levels, releases, events with cited triggers.

Constraints (do not violate):
- No allocation percentages — directional only
- Note Singapore-only / freight / physical OTC as framework-only but
  still enumerate them
- Cite specific instruments and price levels
- Source attribution inline ([wsj], [hfi_subscriber], Sparta Ep N transcript)
- 600 words maximum
- Output pure markdown, no preamble or signoff

Snapshot — {now}

## Prices
{prices_md}

## Derived Spreads
{spreads_md}

## EIA Weekly Stocks (latest print)
{eia_md or '(no EIA data yet)'}

## Open Positions (FUT + OPT)
{positions_md}

## Sparta trade ideas (last 3 episodes, from transcripts)
{sparta_md}

## Headline Feed (titles only)
{news_md}

## Enriched articles (full text — read these closely)
{enriched_md}

## Podcast transcripts (read these closely)
{transcripts_md}
"""


async def _claude_body(data: dict) -> str | None:
    """Invoke claude CLI for the analysis body. Returns None on failure."""
    if not shutil.which(CLAUDE_CLI):
        return None
    prompt = _build_claude_prompt(data)
    try:
        # Use --print (-p) for non-interactive output. Skip --bare so the
        # CLI uses the user's existing OAuth login (Claude.app / claude.ai)
        # — no ANTHROPIC_API_KEY env var needed.
        # --output-format text keeps the result clean for storage.
        proc = await asyncio.create_subprocess_exec(
            CLAUDE_CLI, "-p", prompt, "--output-format", "text",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await asyncio.wait_for(
            proc.communicate(), timeout=CLAUDE_TIMEOUT_SECONDS
        )
        if proc.returncode != 0:
            logger.warning("claude CLI returned %d: %s", proc.returncode,
                            stderr.decode()[:300])
            return None
        return stdout.decode().strip()
    except asyncio.TimeoutError:
        logger.warning("claude CLI timed out after %ds", CLAUDE_TIMEOUT_SECONDS)
        try:
            proc.kill()
        except Exception:  # noqa: BLE001
            pass
        return None
    except Exception as exc:  # noqa: BLE001
        logger.warning("claude CLI error: %s", exc)
        return None


async def run_synthesis() -> dict[str, Any]:
    """Run the synthesis pass. Writes to analysis_runs. Returns the row."""
    data = _build_data_context()
    headline, triggered = _compute_headline_and_alert(data)

    # Prefer Claude CLI body; fall back to rule-based if unavailable/slow
    body = await _claude_body(data)
    model = "claude-cli"
    if body is None:
        body = _rule_based_body(data)
        model = "rule-based-v1"

    with get_conn() as conn:
        conn.execute(
            """
            INSERT INTO analysis_runs (summary, body, triggered_alert, model)
            VALUES (?, ?, ?, ?)
            """,
            [headline, body, triggered, model],
        )

    if triggered:
        await notify("Research — material change", headline)

    logger.info("synthesis ok: %s (alert=%s, model=%s)", headline, triggered, model)
    return {"headline": headline, "triggered_alert": triggered, "model": model}


def latest_analysis() -> dict | None:
    """Most recent synthesis row."""
    with get_conn() as conn:
        row = conn.execute(
            """
            SELECT run_at, summary, body, triggered_alert, model
            FROM analysis_runs
            ORDER BY run_at DESC
            LIMIT 1
            """
        ).fetchone()
        if not row:
            return None
        return {
            "run_at": row[0],
            "summary": row[1],
            "body": row[2],
            "triggered_alert": row[3],
            "model": row[4],
        }
